name: Issues Logger

on:
  issues:
    types: [opened, edited, closed]

jobs:
  log-issue-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue event details
        run: echo "Issue Event: ${{ toJson(github.event) }}"
